import { createContext, useContext, useEffect, useState } from 'react'
import { http } from '@/services/http.js'

const AuthCtx = createContext(null)

export function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [booting, setBooting] = useState(true);


  useEffect(() => {
    const cached = localStorage.getItem('authUser')
    if (cached) setUser(JSON.parse(cached))

      // session change
      ; (async () => {
        try {
          const r = await fetch('/api/session', { credentials: 'include' })
          if (r.ok) {
            const data = await r.json()
            if (data?.user) {
              setUser(data.user)
              localStorage.setItem('authUser', JSON.stringify(data.user))
            } else {
              setUser(null)
              localStorage.removeItem('authUser')
            }
          }
        } finally {
          setBooting(false)
        }
      })()
  }, [])

  // currently not needed, may be needed for functionality later
  // async function login(display_name, password) {
  //   const data = await http.post('/api/login', { display_name, password })
  //   setUser(data.user)
  //   localStorage.setItem('authUser', JSON.stringify(data.user))
  //   return data.user
  // }

  async function logout() {
    try {
      await http.post('/api/logout', {})
    } finally {
      setUser(null)
      localStorage.removeItem('authUser')
    }
  }


  return (
    <AuthCtx.Provider value={{ user, setUser, booting, logout }}>
      {children}
    </AuthCtx.Provider>
  )
}

export function useAuth() {
  return useContext(AuthCtx)
}


// THIS FILE IS COMPLETE. DO NOT EDIT THIS FILE UNLESS FUNCTIONALITY IS
// VERY BROKEN SOMEWHERE IN THE CODE.
// FINSHED 9.28.25
// ADDED HELPER FOR LOGOUT LOGIC. THIS SHOULD NOT NEED TO BE TOUCHED AFTER THIS.
// FINISHED 10.6.25
// ADDED HTTP CALLS FROM SERVICES HTTPAPI. THIS IS THE NEW WAY OF HANDLING
// API CALLS IN THE FRONT-END FOR SERVERS AND LOGIN RELATED THINGS
// FINISHED 10.20.25
// WORKING ON SESSIONS FIX, ADDING REQUIRED CODE AND CONFIG FIXES
// FINISHED 11.12.25